market_data_connection_settings:
  bitstamp:
    api_url: https://www.bitstamp.net/api/v2/
    tickers:
      btcusd:
        symbol: btcusd
        start_date: 2011-01-01
    request_urls:
      ohlc:
        endpoint: ohlc/
        params:
          step:
            name: step
            description: timeframe in seconds
            default_value: 86400
          start:
            name: start
            description: unix timestamp from when ohlc data will be started
          limit:
            name: limit
            description: Limit ohlc results (min - 1, max - 1000)

analysis_config:
  btc_halvings:
    display_name: BTC Halvings
    dates:
      - display_name: btc_1st_halving
        date: 2012-11-28
      - display_name: btc_2nd_halving
        date: 2016-07-09
      - display_name: btc_3rd_halving
        date: 2020-05-11
  btc_bull_cycles:
    display_name: BTC-USD Bull Cycles
    cycles:
      - display_name: btc_run_1st
        start_date: 2011-11-21
        end_date: 2013-11-29
      - display_name: btc_run_2nd
        start_date: 2015-01-14
        end_date: 2017-12-17
      - display_name: btc_run_3rd
        start_date: 2018-12-15
        end_date: 2099-01-01