market_data_connection_settings:
  bitstamp:
    api_url: https://www.bitstamp.net/api/v2/
    tickers:
      btcusd:
        symbol: btcusd
        start_date: '2012-01-01'
    request_urls:
      ohlc:
        endpoint: ohlc/
        params:
          step:
            name: step
            description: timeframe in seconds
            default_value: 86400
          start:
            name: start
            description: unix timestamp from when ohlc data will be started
          limit:
            name: limit
            description: Limit ohlc results (min - 1, max - 1000)
